### ISSUE TITLE
Words don't break properly

### ISSUE THREAD

**Issue by adriancuadrado** [npm/documentation#1475]
![Image](https://github.com/user-attachments/assets/4925132d-086e-4369-be6a-c6f970de3e56)

My screen has a width of 1920px. The cause seems to be this CSS rule:

![Image](https://github.com/user-attachments/assets/1b00785a-b85d-4d84-a102-cbbc5726f715)

```css
.fqlkab li {
    word-break: break-all;
}
```
